### ISSUE TITLE
request feature support for wayland

### ISSUE THREAD

**Issue by cooukiez** [NinoDS/clipboard#2]
you cannot use xclip on wayland compositors, please add support for [wl-clipboard](https://github.com/bugaevc/wl-clipboard)

thanks in advance

**Comment by NinoDS** [comment]
what about implementing it yourself and making a PR?

**Comment by cooukiez** [comment]
i dont have time for it right now

**Comment by NinoDS** [comment]
does it work for you?

**Comment by cooukiez** [comment]
yess, thank you for your hard labor
